version: '3'

vars:
  API_DIR: ./api
  CACHE_DIR: ~/.cache/sochoa.dev

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task -l

  setup:
    desc: Setup local development environment
    cmds:
      - echo "🔧 Setting up local development environment..."
      - mkdir -p {{.CACHE_DIR}}
      - cd {{.API_DIR}} && go mod download
      - echo "✅ Setup complete!"
      - echo "Run 'task api' to start the API"

  api:
    desc: Start the API server
    dir: '{{.API_DIR}}'
    cmds:
      - go build -o api ./
      - ./api
    env:
      DEV_MODE: "true"
      DEV_USER_ROLE: "admin"
      LOG_LEVEL: "debug"

  api:dev:
    desc: Start API with hot-reload (requires air)
    dir: '{{.API_DIR}}'
    cmds:
      - which air > /dev/null || (echo "Installing air..." && go install github.com/cosmtrek/air@latest)
      - air
    env:
      DEV_MODE: "true"
      DEV_USER_ROLE: "admin"
      LOG_LEVEL: "debug"

  api:build:
    desc: Build API binary
    dir: '{{.API_DIR}}'
    cmds:
      - go build -o api ./

  api:test:
    desc: Run API tests
    dir: '{{.API_DIR}}'
    cmds:
      - go test ./...

  api:clean:
    desc: Clean API build artifacts
    dir: '{{.API_DIR}}'
    cmds:
      - rm -f api
      - rm -f {{.CACHE_DIR}}/api.db
      - echo "✅ Cleaned API build and database"

  db:reset:
    desc: Reset the database (delete and recreate)
    cmds:
      - rm -f {{.CACHE_DIR}}/api.db
      - echo "✅ Database reset. Run 'task api' to recreate it."

  db:shell:
    desc: Open SQLite database shell
    cmds:
      - sqlite3 {{.CACHE_DIR}}/api.db

  logs:
    desc: Show API database location and logs info
    cmds:
      - echo "📁 Database: {{.CACHE_DIR}}/api.db"
      - echo "📝 Logs: Sent to stdout (structured JSON)"
      - echo "🔗 Swagger UI: http://localhost:8080/"

  ui:
    desc: Start the UI development server (requires Node.js)
    dir: './ui'
    cmds:
      - npm install
      - npm run dev

  ui:build:
    desc: Build UI for production
    dir: './ui'
    cmds:
      - npm install
      - npm run build

  full:dev:
    desc: Start both API and UI for full-stack development
    cmds:
      - task -p api ui
    env:
      DEV_MODE: "true"
      DEV_USER_ROLE: "admin"
      LOG_LEVEL: "debug"
